name: bulid test run potofpolio
on:
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:  code action
        uses: actions/checkout@v3
      - name : moving into potofolio
        run: cd potofolio
        run: pwd
        run: ls
      - name: Install dependencies
        run: npm install
      - name: iam going start code
        run: npm run start