name: bulid test run potofpolio
on:
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:  code action
        uses: actions/checkout@v3
      - name: iam going start code
        run: npm run start